# config/token.yaml
# bot_token:
# websrv_token:

# config/config.yaml
bot:
  host: 0.0.0.0
  port: 5002
  cert_path: cert/bot-api-parusinf-ru.crt
  key_path: cert/bot-api-parusinf-ru.key
  api_server_url: 'http://192.168.1.72:5000'

webhook:
  url: https://api.parusinf.ru
  cert_path: cert/api-parusinf-ru.crt

websrv:
  url: https://api.parusinf.ru
  cert_path: cert/api-parusinf-ru.crt

sqlite:
  database: /var/lib/sqlite/tsheebot.db
  echo: False

developer:
  name: Павел Никитин
  telegram: '@nikitinpa'

use_log_file: True
log_file: /tmp/tsheebot.log

use_pid_file: True
pid_file: /tmp/tsheebot.pid
